baseURL = "https://imbuto-grants.github.io"
title = "Imbuto Grants"
theme = "imbuto-theme"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

    [[menu.main]]
    identifier = "application"
    name = "Applications"
    url = "/application"
    weight = 20
